CREATE TABLE ACCOUNT (
	ACCOUNT_ID NUMBER,
	NAME VARCHAR2(100),
	ID VARCHAR2(100),
	PASS VARCHAR2(100),
	BIRTHDAY DATE,
	GENDER CHAR(3),
	POST NUMBER,
	ADDRESS VARCHAR2(300),
	ADDRESS2 VARCHAR2(300),
	EMAIL VARCHAR2(100),
	PHONE CHAR(13),
	PHONE2 VARCHAR2(20),
	MAIL_RECV CHAR(1) CONSTRAINT MAIL_RECV_CK CHECK (MAIL_RECV IN ('0', '1')),
	SMS_RECV CHAR(1) CONSTRAINT SMS_RECV_CK CHECK (SMS_RECV IN ('0', '1')),
	CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE PRODUCT (
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	NAME VARCHAR2(100),
	PRODUCT_SIZE VARCHAR2(50),
	PRICE NUMBER,
	DESCRIPTION VARCHAR2(1000),
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID, COLOR)
);

CREATE TABLE STOCK (
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	STOCK NUMBER,
	CONSTRAINT STOCK_PK PRIMARY KEY (PRODUCT_ID, COLOR)
);

CREATE TABLE CART (
	ACCOUNT_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	COUNT NUMBER,
	CONSTRAINT CART_PK PRIMARY KEY (ACCOUNT_ID, PRODUCT_ID, COLOR)
);

CREATE TABLE ORDERED (
	ORDER_ID NUMBER,
	ACCOUNT_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	ORDER_COUNT NUMBER,
	ORDER_DATE DATE,
	POST NUMBER,
	ADDRESS VARCHAR2(300),
	ADDRESS2 VARCHAR2(300),
	ORDER_MESSAGE VARCHAR2(300),
	PAY VARCHAR2(50),
	TOTAL NUMBER,
	CONSTRAINT ORDERED_PK PRIMARY KEY (ORDER_ID)
);

CREATE TABLE WISH_LIST (
	ACCOUNT_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	CONSTRAINT WISH_LIST_PK PRIMARY KEY (ACCOUNT_ID, PRODUCT_ID, COLOR)
);

CREATE TABLE REVIEW (
	REVIEW_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	TITLE VARCHAR2(300),
	CONTENT VARCHAR2(4000),
	ACCOUNT_ID NUMBER,
	POSTING_DATE DATE,
	VIEWS NUMBER,
	CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEW_ID)
);

CREATE TABLE QNA (
	QNA_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	TITLE VARCHAR2(300),
	CONTENT VARCHAR2(4000),
	ACCOUNT_ID NUMBER,
	POSTING_DATE DATE,
	VIEWS NUMBER,
	CONSTRAINT QNA_PK PRIMARY KEY (QNA_ID)
);

CREATE TABLE NOTICE (
	NOTICE_ID NUMBER,
	TITLE VARCHAR2(300),
	CONTENT VARCHAR2(4000),
	ACCOUNT_ID NUMBER,
	POSTING_DATE DATE,
	VIEWS NUMBER,
	CONSTRAINT NOTICE_PK PRIMARY KEY (NOTICE_ID)
);

CREATE TABLE WITHDRAW_ACCOUNT (
	ACCOUNT_ID NUMBER,
	REASON VARCHAR2(4000),
	WITHDRAW_DATE DATE,
	CONSTRAINT WITHDRAW_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
);

