-- 주문 테이블
CREATE TABLE ORDERED (
	ORDER_ID NUMBER,
	ACCOUNT_ID NUMBER,
	PRODUCT_ID NUMBER,
	COLOR VARCHAR2(50),
	ORDER_COUNT NUMBER,
	ORDER_DATE DATE,
	POST NUMBER,
	ADDRESS VARCHAR2(300),
	ADDRESS2 VARCHAR2(300),
	ORDER_MESSAGE VARCHAR2(300),
	PAY VARCHAR2(50),
	TOTAL NUMBER,
	CONSTRAINT ORDERED_PK PRIMARY KEY (ORDER_ID)
);

-- 210215: ORDER_ID 생성 시퀀스 추가
CREATE SEQUENCE ORDER_ID_SEQ
	START WITH 1
	INCREMENT BY 1;
--주문입력
INSERT INTO ORDERED values(prod2_seq.nextval,'두부볼',18000,100,sysdate,
'화소반',sysdate,'이채영');



-- 탈퇴회원 테이블
CREATE TABLE WITHDRAW_ACCOUNT (
	ACCOUNT_ID NUMBER,
	REASON VARCHAR2(4000),
	WITHDRAW_DATE DATE,
	CONSTRAINT WITHDRAW_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
);